#!/usr/bin/env python3
"""Mirror the OrderHub knowledge base into this repo as markdown.

Reads the OrderHub kb-export endpoint and writes one markdown file per
published public article under orderhub/<category>/<slug>.md, plus an index at
orderhub/README.md. Files for articles no longer returned are removed. Only the
orderhub/ folder is ever touched.

Environment:
  ORDERHUB_KB_URL  full URL of the kb-export endpoint
  ORDERHUB_KB_KEY  API key, sent as the X-API-Key header
  ORDERHUB_KB_FILE optional: read a local JSON file instead (for testing)

Exits 0 without changes when the URL or key is not configured yet.
"""
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(os.environ.get("REPO_ROOT", ".")).resolve()
OUT = ROOT / "orderhub"
MARKER = "<!-- generated by scripts/orderhub_kb_sync.py from the OrderHub knowledge base. Do not edit here: edit the article in OrderHub. -->"


def slugify(text, fallback):
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return s[:80] or fallback


def load_payload():
    local = os.environ.get("ORDERHUB_KB_FILE")
    if local:
        return json.loads(Path(local).read_text(encoding="utf-8"))
    url = os.environ.get("ORDERHUB_KB_URL", "").strip()
    key = os.environ.get("ORDERHUB_KB_KEY", "").strip()
    if not url or not key:
        print("ORDERHUB_KB_URL or ORDERHUB_KB_KEY not set, nothing to do.")
        sys.exit(0)
    req = urllib.request.Request(url, headers={"X-API-Key": key, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def body_to_markdown(a):
    if a.get("body_markdown"):
        return a["body_markdown"].strip()
    if a.get("body_html"):
        from markdownify import markdownify
        return markdownify(a["body_html"], heading_style="ATX").strip()
    return ""


def yaml_str(v):
    return json.dumps("" if v is None else str(v), ensure_ascii=False)


def render(a):
    lines = ["---"]
    for k in ("title", "id", "category", "updated_at", "source_url"):
        lines.append(f"{k}: {yaml_str(a.get(k))}")
    lines += ["---", "", MARKER, "", f"# {a.get('title', '').strip()}", ""]
    body = body_to_markdown(a)
    # Drop a leading H1 that repeats the title.
    body = re.sub(r"^#\s+" + re.escape(a.get("title", "").strip()) + r"\s*\n+", "", body)
    lines.append(body)
    return "\n".join(lines).rstrip() + "\n"


def main():
    payload = load_payload()
    articles = payload.get("articles", payload if isinstance(payload, list) else [])
    keep = [a for a in articles
            if (a.get("status") or "published") == "published"
            and (a.get("visibility") or "public") == "public"]
    if not keep:
        # An empty answer is far more likely a fault than a deleted knowledge base.
        print("Endpoint returned no public articles; refusing to wipe orderhub/.")
        sys.exit(1)

    OUT.mkdir(exist_ok=True)
    written, used = set(), set()
    index = {}
    for a in sorted(keep, key=lambda x: ((x.get("category") or ""), (x.get("title") or ""))):
        aid = str(a.get("id", ""))
        cat = slugify(a.get("category"), "general")
        slug = slugify(a.get("slug") or a.get("title"), aid[:8] or "article")
        rel = f"{cat}/{slug}.md"
        if rel in used:  # same title twice in one category
            rel = f"{cat}/{slug}-{aid[:8]}.md"
        used.add(rel)
        path = OUT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(a), encoding="utf-8")
        written.add(path.resolve())
        index.setdefault(a.get("category") or "General", []).append((a.get("title", ""), rel, a.get("updated_at", "")))

    # Remove generated files that are no longer in OrderHub. Hand-written files are left alone.
    removed = 0
    for p in OUT.rglob("*.md"):
        if p.name == "README.md" or p.resolve() in written:
            continue
        if MARKER in p.read_text(encoding="utf-8", errors="ignore"):
            p.unlink()
            removed += 1
    for d in sorted(OUT.rglob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()

    idx = ["# OrderHub knowledge base", "", MARKER, "",
           "Mirror of the help articles inside OrderHub (orderhub.pixfizz.com). "
           "Updated automatically every night. The source of truth is OrderHub: edit articles there, not here. "
           "For the curated overview see `45_ORDERHUB.md`.", "",
           f"{len(keep)} articles.", ""]
    for cat in sorted(index):
        idx += [f"## {cat}", ""]
        for title, rel, upd in index[cat]:
            idx.append(f"- [{title}]({rel})" + (f" (updated {str(upd)[:10]})" if upd else ""))
        idx.append("")
    (OUT / "README.md").write_text("\n".join(idx), encoding="utf-8")
    print(f"Wrote {len(keep)} articles, removed {removed}.")


if __name__ == "__main__":
    main()
